Add GitHub actions and adapt existing one to our name schema
MiSArch/keycloak pull request #2
Opened 2024-01-24 23:51 UTC by delvh

2024-01-26 20:11 UTC, nk-coding requested changes, later dismissed

2024-01-26 20:11 UTC, nk-coding commented on .github/workflows/update-infrastructure-docker.yaml
> +          cd user
Isn't the submodule called keycloak)

2024-01-31 13:08 UTC, delvh commented on .github/workflows/update-infrastructure-docker.yaml
> +          cd user
Yep. Copy-paste error. Fixed now.

2024-01-31 14:41 UTC, nk-coding approved these changes

2024-01-31 16:23 UTC, delvh commented
I'll have to wait for misarch/infrastructure-docker#72 to merge or the update would be overwritten.

2024-02-01 10:00 UTC, merged